// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.15.8
// source: member/member.proto

package member

import (
	general "github.com/paper-trade-chatbot/be-proto/general"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatusType int32

const (
	StatusType_StatusType_None       StatusType = 0
	StatusType_StatusType_Enabled    StatusType = 1
	StatusType_StatusType_Suppressed StatusType = 2
	StatusType_StatusType_Freezed    StatusType = 3
	StatusType_StatusType_Disabled   StatusType = 4
	StatusType_StatusType_Discard    StatusType = 5
	StatusType_StatusType_Derived    StatusType = 6
)

// Enum value maps for StatusType.
var (
	StatusType_name = map[int32]string{
		0: "StatusType_None",
		1: "StatusType_Enabled",
		2: "StatusType_Suppressed",
		3: "StatusType_Freezed",
		4: "StatusType_Disabled",
		5: "StatusType_Discard",
		6: "StatusType_Derived",
	}
	StatusType_value = map[string]int32{
		"StatusType_None":       0,
		"StatusType_Enabled":    1,
		"StatusType_Suppressed": 2,
		"StatusType_Freezed":    3,
		"StatusType_Disabled":   4,
		"StatusType_Discard":    5,
		"StatusType_Derived":    6,
	}
)

func (x StatusType) Enum() *StatusType {
	p := new(StatusType)
	*p = x
	return p
}

func (x StatusType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusType) Descriptor() protoreflect.EnumDescriptor {
	return file_member_member_proto_enumTypes[0].Descriptor()
}

func (StatusType) Type() protoreflect.EnumType {
	return &file_member_member_proto_enumTypes[0]
}

func (x StatusType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatusType.Descriptor instead.
func (StatusType) EnumDescriptor() ([]byte, []int) {
	return file_member_member_proto_rawDescGZIP(), []int{0}
}

type VerifyStatus int32

const (
	VerifyStatus_VerifyStatus_None       VerifyStatus = 0
	VerifyStatus_VerifyStatus_Unverified VerifyStatus = 1
	VerifyStatus_VerifyStatus_Pending    VerifyStatus = 2
	VerifyStatus_VerifyStatus_Verified   VerifyStatus = 3
	VerifyStatus_VerifyStatus_Failed     VerifyStatus = 4
)

// Enum value maps for VerifyStatus.
var (
	VerifyStatus_name = map[int32]string{
		0: "VerifyStatus_None",
		1: "VerifyStatus_Unverified",
		2: "VerifyStatus_Pending",
		3: "VerifyStatus_Verified",
		4: "VerifyStatus_Failed",
	}
	VerifyStatus_value = map[string]int32{
		"VerifyStatus_None":       0,
		"VerifyStatus_Unverified": 1,
		"VerifyStatus_Pending":    2,
		"VerifyStatus_Verified":   3,
		"VerifyStatus_Failed":     4,
	}
)

func (x VerifyStatus) Enum() *VerifyStatus {
	p := new(VerifyStatus)
	*p = x
	return p
}

func (x VerifyStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VerifyStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_member_member_proto_enumTypes[1].Descriptor()
}

func (VerifyStatus) Type() protoreflect.EnumType {
	return &file_member_member_proto_enumTypes[1]
}

func (x VerifyStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VerifyStatus.Descriptor instead.
func (VerifyStatus) EnumDescriptor() ([]byte, []int) {
	return file_member_member_proto_rawDescGZIP(), []int{1}
}

type VerifyType int32

const (
	VerifyType_VerifyType_Phone VerifyType = 0
	VerifyType_VerifyType_Mail  VerifyType = 1
)

// Enum value maps for VerifyType.
var (
	VerifyType_name = map[int32]string{
		0: "VerifyType_Phone",
		1: "VerifyType_Mail",
	}
	VerifyType_value = map[string]int32{
		"VerifyType_Phone": 0,
		"VerifyType_Mail":  1,
	}
)

func (x VerifyType) Enum() *VerifyType {
	p := new(VerifyType)
	*p = x
	return p
}

func (x VerifyType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VerifyType) Descriptor() protoreflect.EnumDescriptor {
	return file_member_member_proto_enumTypes[2].Descriptor()
}

func (VerifyType) Type() protoreflect.EnumType {
	return &file_member_member_proto_enumTypes[2]
}

func (x VerifyType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VerifyType.Descriptor instead.
func (VerifyType) EnumDescriptor() ([]byte, []int) {
	return file_member_member_proto_rawDescGZIP(), []int{2}
}

type Member struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            uint64       `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Account       string       `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	Mail          string       `protobuf:"bytes,3,opt,name=mail,proto3" json:"mail,omitempty"`
	LineID        string       `protobuf:"bytes,4,opt,name=lineID,proto3" json:"lineID,omitempty"`
	CountryCode   string       `protobuf:"bytes,5,opt,name=countryCode,proto3" json:"countryCode,omitempty"`
	Phone         string       `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"`
	GroupID       int64        `protobuf:"varint,7,opt,name=groupID,proto3" json:"groupID,omitempty"`
	Status        StatusType   `protobuf:"varint,8,opt,name=status,proto3,enum=member.StatusType" json:"status,omitempty"`
	VerifyStatus  VerifyStatus `protobuf:"varint,9,opt,name=verifyStatus,proto3,enum=member.VerifyStatus" json:"verifyStatus,omitempty"`
	CreatedAtUnix int64        `protobuf:"varint,10,opt,name=createdAtUnix,proto3" json:"createdAtUnix,omitempty"`
	LoginAtUnix   int64        `protobuf:"varint,11,opt,name=loginAtUnix,proto3" json:"loginAtUnix,omitempty"`
}

func (x *Member) Reset() {
	*x = Member{}
	if protoimpl.UnsafeEnabled {
		mi := &file_member_member_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Member) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Member) ProtoMessage() {}

func (x *Member) ProtoReflect() protoreflect.Message {
	mi := &file_member_member_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Member.ProtoReflect.Descriptor instead.
func (*Member) Descriptor() ([]byte, []int) {
	return file_member_member_proto_rawDescGZIP(), []int{0}
}

func (x *Member) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Member) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *Member) GetMail() string {
	if x != nil {
		return x.Mail
	}
	return ""
}

func (x *Member) GetLineID() string {
	if x != nil {
		return x.LineID
	}
	return ""
}

func (x *Member) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *Member) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Member) GetGroupID() int64 {
	if x != nil {
		return x.GroupID
	}
	return 0
}

func (x *Member) GetStatus() StatusType {
	if x != nil {
		return x.Status
	}
	return StatusType_StatusType_None
}

func (x *Member) GetVerifyStatus() VerifyStatus {
	if x != nil {
		return x.VerifyStatus
	}
	return VerifyStatus_VerifyStatus_None
}

func (x *Member) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

func (x *Member) GetLoginAtUnix() int64 {
	if x != nil {
		return x.LoginAtUnix
	}
	return 0
}

type CreateMemberReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account       string       `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Password      string       `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Mail          string       `protobuf:"bytes,3,opt,name=mail,proto3" json:"mail,omitempty"`
	LineID        string       `protobuf:"bytes,4,opt,name=lineID,proto3" json:"lineID,omitempty"`
	Status        StatusType   `protobuf:"varint,5,opt,name=status,proto3,enum=member.StatusType" json:"status,omitempty"`
	VerifyStatus  VerifyStatus `protobuf:"varint,6,opt,name=verifyStatus,proto3,enum=member.VerifyStatus" json:"verifyStatus,omitempty"`
	GroupID       int64        `protobuf:"varint,7,opt,name=groupID,proto3" json:"groupID,omitempty"`
	CreatedAtUnix int64        `protobuf:"varint,8,opt,name=createdAtUnix,proto3" json:"createdAtUnix,omitempty"`
}

func (x *CreateMemberReq) Reset() {
	*x = CreateMemberReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_member_member_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMemberReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMemberReq) ProtoMessage() {}

func (x *CreateMemberReq) ProtoReflect() protoreflect.Message {
	mi := &file_member_member_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMemberReq.ProtoReflect.Descriptor instead.
func (*CreateMemberReq) Descriptor() ([]byte, []int) {
	return file_member_member_proto_rawDescGZIP(), []int{1}
}

func (x *CreateMemberReq) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *CreateMemberReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateMemberReq) GetMail() string {
	if x != nil {
		return x.Mail
	}
	return ""
}

func (x *CreateMemberReq) GetLineID() string {
	if x != nil {
		return x.LineID
	}
	return ""
}

func (x *CreateMemberReq) GetStatus() StatusType {
	if x != nil {
		return x.Status
	}
	return StatusType_StatusType_None
}

func (x *CreateMemberReq) GetVerifyStatus() VerifyStatus {
	if x != nil {
		return x.VerifyStatus
	}
	return VerifyStatus_VerifyStatus_None
}

func (x *CreateMemberReq) GetGroupID() int64 {
	if x != nil {
		return x.GroupID
	}
	return 0
}

func (x *CreateMemberReq) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

type CreateMemberRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateMemberRes) Reset() {
	*x = CreateMemberRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_member_member_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMemberRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMemberRes) ProtoMessage() {}

func (x *CreateMemberRes) ProtoReflect() protoreflect.Message {
	mi := &file_member_member_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMemberRes.ProtoReflect.Descriptor instead.
func (*CreateMemberRes) Descriptor() ([]byte, []int) {
	return file_member_member_proto_rawDescGZIP(), []int{2}
}

type GetMemberReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Member:
	//	*GetMemberReq_Id
	//	*GetMemberReq_Account
	//	*GetMemberReq_Mail
	//	*GetMemberReq_LineID
	Member isGetMemberReq_Member `protobuf_oneof:"member"`
}

func (x *GetMemberReq) Reset() {
	*x = GetMemberReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_member_member_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMemberReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMemberReq) ProtoMessage() {}

func (x *GetMemberReq) ProtoReflect() protoreflect.Message {
	mi := &file_member_member_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMemberReq.ProtoReflect.Descriptor instead.
func (*GetMemberReq) Descriptor() ([]byte, []int) {
	return file_member_member_proto_rawDescGZIP(), []int{3}
}

func (m *GetMemberReq) GetMember() isGetMemberReq_Member {
	if m != nil {
		return m.Member
	}
	return nil
}

func (x *GetMemberReq) GetId() int32 {
	if x, ok := x.GetMember().(*GetMemberReq_Id); ok {
		return x.Id
	}
	return 0
}

func (x *GetMemberReq) GetAccount() string {
	if x, ok := x.GetMember().(*GetMemberReq_Account); ok {
		return x.Account
	}
	return ""
}

func (x *GetMemberReq) GetMail() string {
	if x, ok := x.GetMember().(*GetMemberReq_Mail); ok {
		return x.Mail
	}
	return ""
}

func (x *GetMemberReq) GetLineID() string {
	if x, ok := x.GetMember().(*GetMemberReq_LineID); ok {
		return x.LineID
	}
	return ""
}

type isGetMemberReq_Member interface {
	isGetMemberReq_Member()
}

type GetMemberReq_Id struct {
	Id int32 `protobuf:"varint,1,opt,name=id,proto3,oneof"`
}

type GetMemberReq_Account struct {
	Account string `protobuf:"bytes,2,opt,name=account,proto3,oneof"`
}

type GetMemberReq_Mail struct {
	Mail string `protobuf:"bytes,3,opt,name=mail,proto3,oneof"`
}

type GetMemberReq_LineID struct {
	LineID string `protobuf:"bytes,4,opt,name=lineID,proto3,oneof"`
}

func (*GetMemberReq_Id) isGetMemberReq_Member() {}

func (*GetMemberReq_Account) isGetMemberReq_Member() {}

func (*GetMemberReq_Mail) isGetMemberReq_Member() {}

func (*GetMemberReq_LineID) isGetMemberReq_Member() {}

type GetMemberRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Member *Member `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`
}

func (x *GetMemberRes) Reset() {
	*x = GetMemberRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_member_member_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMemberRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMemberRes) ProtoMessage() {}

func (x *GetMemberRes) ProtoReflect() protoreflect.Message {
	mi := &file_member_member_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMemberRes.ProtoReflect.Descriptor instead.
func (*GetMemberRes) Descriptor() ([]byte, []int) {
	return file_member_member_proto_rawDescGZIP(), []int{4}
}

func (x *GetMemberRes) GetMember() *Member {
	if x != nil {
		return x.Member
	}
	return nil
}

type GetMembersReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pagination *general.Pagination `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (x *GetMembersReq) Reset() {
	*x = GetMembersReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_member_member_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMembersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMembersReq) ProtoMessage() {}

func (x *GetMembersReq) ProtoReflect() protoreflect.Message {
	mi := &file_member_member_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMembersReq.ProtoReflect.Descriptor instead.
func (*GetMembersReq) Descriptor() ([]byte, []int) {
	return file_member_member_proto_rawDescGZIP(), []int{5}
}

func (x *GetMembersReq) GetPagination() *general.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type GetMembersRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Member         []*Member               `protobuf:"bytes,1,rep,name=member,proto3" json:"member,omitempty"`
	PaginationInfo *general.PaginationInfo `protobuf:"bytes,2,opt,name=paginationInfo,proto3" json:"paginationInfo,omitempty"`
}

func (x *GetMembersRes) Reset() {
	*x = GetMembersRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_member_member_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMembersRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMembersRes) ProtoMessage() {}

func (x *GetMembersRes) ProtoReflect() protoreflect.Message {
	mi := &file_member_member_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMembersRes.ProtoReflect.Descriptor instead.
func (*GetMembersRes) Descriptor() ([]byte, []int) {
	return file_member_member_proto_rawDescGZIP(), []int{6}
}

func (x *GetMembersRes) GetMember() []*Member {
	if x != nil {
		return x.Member
	}
	return nil
}

func (x *GetMembersRes) GetPaginationInfo() *general.PaginationInfo {
	if x != nil {
		return x.PaginationInfo
	}
	return nil
}

type ModifyMemberReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Member:
	//	*ModifyMemberReq_Id
	//	*ModifyMemberReq_Account
	//	*ModifyMemberReq_Mail
	//	*ModifyMemberReq_LineID
	Member       isModifyMemberReq_Member `protobuf_oneof:"member"`
	Status       *StatusType              `protobuf:"varint,5,opt,name=status,proto3,enum=member.StatusType,oneof" json:"status,omitempty"`
	VerifyStatus *VerifyStatus            `protobuf:"varint,6,opt,name=verifyStatus,proto3,enum=member.VerifyStatus,oneof" json:"verifyStatus,omitempty"`
}

func (x *ModifyMemberReq) Reset() {
	*x = ModifyMemberReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_member_member_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModifyMemberReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyMemberReq) ProtoMessage() {}

func (x *ModifyMemberReq) ProtoReflect() protoreflect.Message {
	mi := &file_member_member_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyMemberReq.ProtoReflect.Descriptor instead.
func (*ModifyMemberReq) Descriptor() ([]byte, []int) {
	return file_member_member_proto_rawDescGZIP(), []int{7}
}

func (m *ModifyMemberReq) GetMember() isModifyMemberReq_Member {
	if m != nil {
		return m.Member
	}
	return nil
}

func (x *ModifyMemberReq) GetId() int32 {
	if x, ok := x.GetMember().(*ModifyMemberReq_Id); ok {
		return x.Id
	}
	return 0
}

func (x *ModifyMemberReq) GetAccount() string {
	if x, ok := x.GetMember().(*ModifyMemberReq_Account); ok {
		return x.Account
	}
	return ""
}

func (x *ModifyMemberReq) GetMail() string {
	if x, ok := x.GetMember().(*ModifyMemberReq_Mail); ok {
		return x.Mail
	}
	return ""
}

func (x *ModifyMemberReq) GetLineID() string {
	if x, ok := x.GetMember().(*ModifyMemberReq_LineID); ok {
		return x.LineID
	}
	return ""
}

func (x *ModifyMemberReq) GetStatus() StatusType {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return StatusType_StatusType_None
}

func (x *ModifyMemberReq) GetVerifyStatus() VerifyStatus {
	if x != nil && x.VerifyStatus != nil {
		return *x.VerifyStatus
	}
	return VerifyStatus_VerifyStatus_None
}

type isModifyMemberReq_Member interface {
	isModifyMemberReq_Member()
}

type ModifyMemberReq_Id struct {
	Id int32 `protobuf:"varint,1,opt,name=id,proto3,oneof"`
}

type ModifyMemberReq_Account struct {
	Account string `protobuf:"bytes,2,opt,name=account,proto3,oneof"`
}

type ModifyMemberReq_Mail struct {
	Mail string `protobuf:"bytes,3,opt,name=mail,proto3,oneof"`
}

type ModifyMemberReq_LineID struct {
	LineID string `protobuf:"bytes,4,opt,name=lineID,proto3,oneof"`
}

func (*ModifyMemberReq_Id) isModifyMemberReq_Member() {}

func (*ModifyMemberReq_Account) isModifyMemberReq_Member() {}

func (*ModifyMemberReq_Mail) isModifyMemberReq_Member() {}

func (*ModifyMemberReq_LineID) isModifyMemberReq_Member() {}

type ModifyMemberRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ModifyMemberRes) Reset() {
	*x = ModifyMemberRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_member_member_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModifyMemberRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyMemberRes) ProtoMessage() {}

func (x *ModifyMemberRes) ProtoReflect() protoreflect.Message {
	mi := &file_member_member_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyMemberRes.ProtoReflect.Descriptor instead.
func (*ModifyMemberRes) Descriptor() ([]byte, []int) {
	return file_member_member_proto_rawDescGZIP(), []int{8}
}

type ResetPasswordReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NewPassword string     `protobuf:"bytes,1,opt,name=newPassword,proto3" json:"newPassword,omitempty"`
	VerifyType  VerifyType `protobuf:"varint,2,opt,name=verifyType,proto3,enum=member.VerifyType" json:"verifyType,omitempty"`
	CountryCode string     `protobuf:"bytes,3,opt,name=countryCode,proto3" json:"countryCode,omitempty"`
	Phone       string     `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Email       string     `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *ResetPasswordReq) Reset() {
	*x = ResetPasswordReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_member_member_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResetPasswordReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPasswordReq) ProtoMessage() {}

func (x *ResetPasswordReq) ProtoReflect() protoreflect.Message {
	mi := &file_member_member_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPasswordReq.ProtoReflect.Descriptor instead.
func (*ResetPasswordReq) Descriptor() ([]byte, []int) {
	return file_member_member_proto_rawDescGZIP(), []int{9}
}

func (x *ResetPasswordReq) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

func (x *ResetPasswordReq) GetVerifyType() VerifyType {
	if x != nil {
		return x.VerifyType
	}
	return VerifyType_VerifyType_Phone
}

func (x *ResetPasswordReq) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *ResetPasswordReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *ResetPasswordReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type ResetPasswordRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *ResetPasswordRes) Reset() {
	*x = ResetPasswordRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_member_member_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResetPasswordRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPasswordRes) ProtoMessage() {}

func (x *ResetPasswordRes) ProtoReflect() protoreflect.Message {
	mi := &file_member_member_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPasswordRes.ProtoReflect.Descriptor instead.
func (*ResetPasswordRes) Descriptor() ([]byte, []int) {
	return file_member_member_proto_rawDescGZIP(), []int{10}
}

func (x *ResetPasswordRes) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeleteMemberReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Member:
	//	*DeleteMemberReq_Id
	//	*DeleteMemberReq_Account
	//	*DeleteMemberReq_Mail
	//	*DeleteMemberReq_LineID
	Member isDeleteMemberReq_Member `protobuf_oneof:"member"`
}

func (x *DeleteMemberReq) Reset() {
	*x = DeleteMemberReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_member_member_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteMemberReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMemberReq) ProtoMessage() {}

func (x *DeleteMemberReq) ProtoReflect() protoreflect.Message {
	mi := &file_member_member_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMemberReq.ProtoReflect.Descriptor instead.
func (*DeleteMemberReq) Descriptor() ([]byte, []int) {
	return file_member_member_proto_rawDescGZIP(), []int{11}
}

func (m *DeleteMemberReq) GetMember() isDeleteMemberReq_Member {
	if m != nil {
		return m.Member
	}
	return nil
}

func (x *DeleteMemberReq) GetId() int32 {
	if x, ok := x.GetMember().(*DeleteMemberReq_Id); ok {
		return x.Id
	}
	return 0
}

func (x *DeleteMemberReq) GetAccount() string {
	if x, ok := x.GetMember().(*DeleteMemberReq_Account); ok {
		return x.Account
	}
	return ""
}

func (x *DeleteMemberReq) GetMail() string {
	if x, ok := x.GetMember().(*DeleteMemberReq_Mail); ok {
		return x.Mail
	}
	return ""
}

func (x *DeleteMemberReq) GetLineID() string {
	if x, ok := x.GetMember().(*DeleteMemberReq_LineID); ok {
		return x.LineID
	}
	return ""
}

type isDeleteMemberReq_Member interface {
	isDeleteMemberReq_Member()
}

type DeleteMemberReq_Id struct {
	Id int32 `protobuf:"varint,1,opt,name=id,proto3,oneof"`
}

type DeleteMemberReq_Account struct {
	Account string `protobuf:"bytes,2,opt,name=account,proto3,oneof"`
}

type DeleteMemberReq_Mail struct {
	Mail string `protobuf:"bytes,3,opt,name=mail,proto3,oneof"`
}

type DeleteMemberReq_LineID struct {
	LineID string `protobuf:"bytes,4,opt,name=lineID,proto3,oneof"`
}

func (*DeleteMemberReq_Id) isDeleteMemberReq_Member() {}

func (*DeleteMemberReq_Account) isDeleteMemberReq_Member() {}

func (*DeleteMemberReq_Mail) isDeleteMemberReq_Member() {}

func (*DeleteMemberReq_LineID) isDeleteMemberReq_Member() {}

type DeleteMemberRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteMemberRes) Reset() {
	*x = DeleteMemberRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_member_member_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteMemberRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMemberRes) ProtoMessage() {}

func (x *DeleteMemberRes) ProtoReflect() protoreflect.Message {
	mi := &file_member_member_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMemberRes.ProtoReflect.Descriptor instead.
func (*DeleteMemberRes) Descriptor() ([]byte, []int) {
	return file_member_member_proto_rawDescGZIP(), []int{12}
}

type CreateMemberGroupReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *CreateMemberGroupReq) Reset() {
	*x = CreateMemberGroupReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_member_member_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMemberGroupReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMemberGroupReq) ProtoMessage() {}

func (x *CreateMemberGroupReq) ProtoReflect() protoreflect.Message {
	mi := &file_member_member_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMemberGroupReq.ProtoReflect.Descriptor instead.
func (*CreateMemberGroupReq) Descriptor() ([]byte, []int) {
	return file_member_member_proto_rawDescGZIP(), []int{13}
}

func (x *CreateMemberGroupReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateMemberGroupRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateMemberGroupRes) Reset() {
	*x = CreateMemberGroupRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_member_member_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMemberGroupRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMemberGroupRes) ProtoMessage() {}

func (x *CreateMemberGroupRes) ProtoReflect() protoreflect.Message {
	mi := &file_member_member_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMemberGroupRes.ProtoReflect.Descriptor instead.
func (*CreateMemberGroupRes) Descriptor() ([]byte, []int) {
	return file_member_member_proto_rawDescGZIP(), []int{14}
}

type GetMemberGroupsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   *uint64 `protobuf:"varint,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	Name *string `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
}

func (x *GetMemberGroupsReq) Reset() {
	*x = GetMemberGroupsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_member_member_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMemberGroupsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMemberGroupsReq) ProtoMessage() {}

func (x *GetMemberGroupsReq) ProtoReflect() protoreflect.Message {
	mi := &file_member_member_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMemberGroupsReq.ProtoReflect.Descriptor instead.
func (*GetMemberGroupsReq) Descriptor() ([]byte, []int) {
	return file_member_member_proto_rawDescGZIP(), []int{15}
}

func (x *GetMemberGroupsReq) GetId() uint64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *GetMemberGroupsReq) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

type MemberGroup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Memo      string `protobuf:"bytes,3,opt,name=memo,proto3" json:"memo,omitempty"`
	CreatedAt int64  `protobuf:"varint,4,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
}

func (x *MemberGroup) Reset() {
	*x = MemberGroup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_member_member_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MemberGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberGroup) ProtoMessage() {}

func (x *MemberGroup) ProtoReflect() protoreflect.Message {
	mi := &file_member_member_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberGroup.ProtoReflect.Descriptor instead.
func (*MemberGroup) Descriptor() ([]byte, []int) {
	return file_member_member_proto_rawDescGZIP(), []int{16}
}

func (x *MemberGroup) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MemberGroup) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MemberGroup) GetMemo() string {
	if x != nil {
		return x.Memo
	}
	return ""
}

func (x *MemberGroup) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type GetMemberGroupsRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MemberGroups []*MemberGroup `protobuf:"bytes,1,rep,name=memberGroups,proto3" json:"memberGroups,omitempty"`
}

func (x *GetMemberGroupsRes) Reset() {
	*x = GetMemberGroupsRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_member_member_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMemberGroupsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMemberGroupsRes) ProtoMessage() {}

func (x *GetMemberGroupsRes) ProtoReflect() protoreflect.Message {
	mi := &file_member_member_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMemberGroupsRes.ProtoReflect.Descriptor instead.
func (*GetMemberGroupsRes) Descriptor() ([]byte, []int) {
	return file_member_member_proto_rawDescGZIP(), []int{17}
}

func (x *GetMemberGroupsRes) GetMemberGroups() []*MemberGroup {
	if x != nil {
		return x.MemberGroups
	}
	return nil
}

type DeleteMemberGroupReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to MemberGroup:
	//	*DeleteMemberGroupReq_Id
	//	*DeleteMemberGroupReq_Name
	MemberGroup isDeleteMemberGroupReq_MemberGroup `protobuf_oneof:"memberGroup"`
}

func (x *DeleteMemberGroupReq) Reset() {
	*x = DeleteMemberGroupReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_member_member_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteMemberGroupReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMemberGroupReq) ProtoMessage() {}

func (x *DeleteMemberGroupReq) ProtoReflect() protoreflect.Message {
	mi := &file_member_member_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMemberGroupReq.ProtoReflect.Descriptor instead.
func (*DeleteMemberGroupReq) Descriptor() ([]byte, []int) {
	return file_member_member_proto_rawDescGZIP(), []int{18}
}

func (m *DeleteMemberGroupReq) GetMemberGroup() isDeleteMemberGroupReq_MemberGroup {
	if m != nil {
		return m.MemberGroup
	}
	return nil
}

func (x *DeleteMemberGroupReq) GetId() uint64 {
	if x, ok := x.GetMemberGroup().(*DeleteMemberGroupReq_Id); ok {
		return x.Id
	}
	return 0
}

func (x *DeleteMemberGroupReq) GetName() string {
	if x, ok := x.GetMemberGroup().(*DeleteMemberGroupReq_Name); ok {
		return x.Name
	}
	return ""
}

type isDeleteMemberGroupReq_MemberGroup interface {
	isDeleteMemberGroupReq_MemberGroup()
}

type DeleteMemberGroupReq_Id struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3,oneof"`
}

type DeleteMemberGroupReq_Name struct {
	Name string `protobuf:"bytes,2,opt,name=name,proto3,oneof"`
}

func (*DeleteMemberGroupReq_Id) isDeleteMemberGroupReq_MemberGroup() {}

func (*DeleteMemberGroupReq_Name) isDeleteMemberGroupReq_MemberGroup() {}

type DeleteMemberGroupRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteMemberGroupRes) Reset() {
	*x = DeleteMemberGroupRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_member_member_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteMemberGroupRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMemberGroupRes) ProtoMessage() {}

func (x *DeleteMemberGroupRes) ProtoReflect() protoreflect.Message {
	mi := &file_member_member_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMemberGroupRes.ProtoReflect.Descriptor instead.
func (*DeleteMemberGroupRes) Descriptor() ([]byte, []int) {
	return file_member_member_proto_rawDescGZIP(), []int{19}
}

var File_member_member_proto protoreflect.FileDescriptor

var file_member_member_proto_rawDesc = []byte{
	0x0a, 0x13, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x2f, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x1a, 0x15, 0x67,
	0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x2f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xde, 0x02, 0x0a, 0x06, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x18, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x61, 0x69,
	0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x16, 0x0a,
	0x06, 0x6c, 0x69, 0x6e, 0x65, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6c,
	0x69, 0x6e, 0x65, 0x49, 0x44, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79,
	0x43, 0x6f, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x72, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x12, 0x2a, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x54, 0x79, 0x70, 0x65, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x38, 0x0a, 0x0c, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x6d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x0c, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x24, 0x0a,
	0x0d, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x55, 0x6e, 0x69, 0x78, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x55,
	0x6e, 0x69, 0x78, 0x12, 0x20, 0x0a, 0x0b, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x41, 0x74, 0x55, 0x6e,
	0x69, 0x78, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x41,
	0x74, 0x55, 0x6e, 0x69, 0x78, 0x22, 0x99, 0x02, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6d,
	0x61, 0x69, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x69, 0x6e, 0x65, 0x49, 0x44, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x6c, 0x69, 0x6e, 0x65, 0x49, 0x44, 0x12, 0x2a, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x6d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x38, 0x0a, 0x0c, 0x76, 0x65, 0x72, 0x69, 0x66,
	0x79, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e,
	0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x0c, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x18, 0x0a, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x12, 0x24, 0x0a, 0x0d, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x55, 0x6e, 0x69, 0x78, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0d, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x55, 0x6e, 0x69,
	0x78, 0x22, 0x11, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x6d, 0x62, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x22, 0x76, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x48, 0x00, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x14, 0x0a, 0x04, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x00, 0x52, 0x04, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x18, 0x0a, 0x06, 0x6c, 0x69, 0x6e, 0x65,
	0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06, 0x6c, 0x69, 0x6e, 0x65,
	0x49, 0x44, 0x42, 0x08, 0x0a, 0x06, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x36, 0x0a, 0x0c,
	0x47, 0x65, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x73, 0x12, 0x26, 0x0a, 0x06,
	0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x06, 0x6d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x22, 0x44, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65,
	0x72, 0x73, 0x52, 0x65, 0x71, 0x12, 0x33, 0x0a, 0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x67, 0x65, 0x6e, 0x65,
	0x72, 0x61, 0x6c, 0x2e, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0a,
	0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x78, 0x0a, 0x0d, 0x47, 0x65,
	0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x12, 0x26, 0x0a, 0x06, 0x6d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x2e, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x06, 0x6d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x12, 0x3f, 0x0a, 0x0e, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x65,
	0x6e, 0x65, 0x72, 0x61, 0x6c, 0x2e, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0e, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x49, 0x6e, 0x66, 0x6f, 0x22, 0x85, 0x02, 0x0a, 0x0f, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x4d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x07, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x07, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x04, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x18, 0x0a, 0x06,
	0x6c, 0x69, 0x6e, 0x65, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06,
	0x6c, 0x69, 0x6e, 0x65, 0x49, 0x44, 0x12, 0x2f, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x2e,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x54, 0x79, 0x70, 0x65, 0x48, 0x01, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x88, 0x01, 0x01, 0x12, 0x3d, 0x0a, 0x0c, 0x76, 0x65, 0x72, 0x69, 0x66,
	0x79, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e,
	0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x48, 0x02, 0x52, 0x0c, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x88, 0x01, 0x01, 0x42, 0x08, 0x0a, 0x06, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x42, 0x09, 0x0a, 0x07, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0x0f, 0x0a, 0x0d, 0x5f,
	0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x11, 0x0a, 0x0f,
	0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x73, 0x22,
	0xb6, 0x01, 0x0a, 0x10, 0x52, 0x65, 0x73, 0x65, 0x74, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x52, 0x65, 0x71, 0x12, 0x20, 0x0a, 0x0b, 0x6e, 0x65, 0x77, 0x50, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6e, 0x65, 0x77, 0x50, 0x61,
	0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x32, 0x0a, 0x0a, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79,
	0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x6d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0a,
	0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x72, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x6f,
	0x6e, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x2c, 0x0a, 0x10, 0x52, 0x65, 0x73, 0x65,
	0x74, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x79, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x07, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x07,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x04, 0x6d, 0x61, 0x69, 0x6c, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x18, 0x0a,
	0x06, 0x6c, 0x69, 0x6e, 0x65, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52,
	0x06, 0x6c, 0x69, 0x6e, 0x65, 0x49, 0x44, 0x42, 0x08, 0x0a, 0x06, 0x6d, 0x65, 0x6d, 0x62, 0x65,
	0x72, 0x22, 0x11, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x65, 0x6d, 0x62, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x22, 0x2a, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x22, 0x16, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x73, 0x22, 0x52, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x4d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x52, 0x65, 0x71, 0x12, 0x13,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x48, 0x00, 0x52, 0x02, 0x69, 0x64,
	0x88, 0x01, 0x01, 0x12, 0x17, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x48, 0x01, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x88, 0x01, 0x01, 0x42, 0x05, 0x0a, 0x03,
	0x5f, 0x69, 0x64, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x63, 0x0a, 0x0b,
	0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x6d, 0x65, 0x6d, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6d,
	0x65, 0x6d, 0x6f, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41,
	0x74, 0x22, 0x4d, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x73, 0x52, 0x65, 0x73, 0x12, 0x37, 0x0a, 0x0c, 0x6d, 0x65, 0x6d, 0x62, 0x65,
	0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x52, 0x0c, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73,
	0x22, 0x4d, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x48, 0x00, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x42, 0x0d, 0x0a, 0x0b, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x22,
	0x16, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x73, 0x2a, 0xb5, 0x01, 0x0a, 0x0a, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x54, 0x79, 0x70, 0x65, 0x12, 0x13, 0x0a, 0x0f, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x54, 0x79, 0x70, 0x65, 0x5f, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x16, 0x0a, 0x12, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65,
	0x64, 0x10, 0x01, 0x12, 0x19, 0x0a, 0x15, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x54, 0x79, 0x70,
	0x65, 0x5f, 0x53, 0x75, 0x70, 0x70, 0x72, 0x65, 0x73, 0x73, 0x65, 0x64, 0x10, 0x02, 0x12, 0x16,
	0x0a, 0x12, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x46, 0x72, 0x65,
	0x65, 0x7a, 0x65, 0x64, 0x10, 0x03, 0x12, 0x17, 0x0a, 0x13, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x54, 0x79, 0x70, 0x65, 0x5f, 0x44, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x10, 0x04, 0x12,
	0x16, 0x0a, 0x12, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x44, 0x69,
	0x73, 0x63, 0x61, 0x72, 0x64, 0x10, 0x05, 0x12, 0x16, 0x0a, 0x12, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x44, 0x65, 0x72, 0x69, 0x76, 0x65, 0x64, 0x10, 0x06, 0x2a,
	0x90, 0x01, 0x0a, 0x0c, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x15, 0x0a, 0x11, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x5f, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x1b, 0x0a, 0x17, 0x56, 0x65, 0x72, 0x69, 0x66,
	0x79, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x55, 0x6e, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69,
	0x65, 0x64, 0x10, 0x01, 0x12, 0x18, 0x0a, 0x14, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x5f, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x10, 0x02, 0x12, 0x19,
	0x0a, 0x15, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x56,
	0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64, 0x10, 0x03, 0x12, 0x17, 0x0a, 0x13, 0x56, 0x65, 0x72,
	0x69, 0x66, 0x79, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64,
	0x10, 0x04, 0x2a, 0x37, 0x0a, 0x0a, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x14, 0x0a, 0x10, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x50,
	0x68, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79,
	0x54, 0x79, 0x70, 0x65, 0x5f, 0x4d, 0x61, 0x69, 0x6c, 0x10, 0x01, 0x32, 0x80, 0x05, 0x0a, 0x0d,
	0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x40, 0x0a,
	0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x17, 0x2e,
	0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x73, 0x12,
	0x37, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x14, 0x2e, 0x6d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x1a, 0x14, 0x2e, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x4d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x73, 0x12, 0x3a, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x4d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x12, 0x15, 0x2e, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x2e,
	0x47, 0x65, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e,
	0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x73, 0x52, 0x65, 0x73, 0x12, 0x40, 0x0a, 0x0c, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x4d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x12, 0x17, 0x2e, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x4d, 0x6f,
	0x64, 0x69, 0x66, 0x79, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e,
	0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x4d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x52, 0x65, 0x73, 0x12, 0x45, 0x0a, 0x0d, 0x52, 0x65, 0x73, 0x65, 0x74, 0x50,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x18, 0x2e, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x2e, 0x52, 0x65, 0x73, 0x65, 0x74, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x52, 0x65,
	0x71, 0x1a, 0x18, 0x2e, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x73, 0x65, 0x74,
	0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x42, 0x0a,
	0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x17, 0x2e,
	0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x2e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x73, 0x22,
	0x00, 0x12, 0x4f, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x6d, 0x62, 0x65,
	0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x1c, 0x2e, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x52, 0x65, 0x71, 0x1a, 0x1c, 0x2e, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52,
	0x65, 0x73, 0x12, 0x49, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x73, 0x12, 0x1a, 0x2e, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x47,
	0x65, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x52, 0x65,
	0x71, 0x1a, 0x1a, 0x2e, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x52, 0x65, 0x73, 0x12, 0x4f, 0x0a,
	0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x12, 0x1c, 0x2e, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71,
	0x1a, 0x1c, 0x2e, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x73, 0x42, 0x30,
	0x5a, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x61, 0x70,
	0x65, 0x72, 0x2d, 0x74, 0x72, 0x61, 0x64, 0x65, 0x2d, 0x63, 0x68, 0x61, 0x74, 0x62, 0x6f, 0x74,
	0x2f, 0x62, 0x65, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_member_member_proto_rawDescOnce sync.Once
	file_member_member_proto_rawDescData = file_member_member_proto_rawDesc
)

func file_member_member_proto_rawDescGZIP() []byte {
	file_member_member_proto_rawDescOnce.Do(func() {
		file_member_member_proto_rawDescData = protoimpl.X.CompressGZIP(file_member_member_proto_rawDescData)
	})
	return file_member_member_proto_rawDescData
}

var file_member_member_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_member_member_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_member_member_proto_goTypes = []interface{}{
	(StatusType)(0),                // 0: member.StatusType
	(VerifyStatus)(0),              // 1: member.VerifyStatus
	(VerifyType)(0),                // 2: member.VerifyType
	(*Member)(nil),                 // 3: member.Member
	(*CreateMemberReq)(nil),        // 4: member.CreateMemberReq
	(*CreateMemberRes)(nil),        // 5: member.CreateMemberRes
	(*GetMemberReq)(nil),           // 6: member.GetMemberReq
	(*GetMemberRes)(nil),           // 7: member.GetMemberRes
	(*GetMembersReq)(nil),          // 8: member.GetMembersReq
	(*GetMembersRes)(nil),          // 9: member.GetMembersRes
	(*ModifyMemberReq)(nil),        // 10: member.ModifyMemberReq
	(*ModifyMemberRes)(nil),        // 11: member.ModifyMemberRes
	(*ResetPasswordReq)(nil),       // 12: member.ResetPasswordReq
	(*ResetPasswordRes)(nil),       // 13: member.ResetPasswordRes
	(*DeleteMemberReq)(nil),        // 14: member.DeleteMemberReq
	(*DeleteMemberRes)(nil),        // 15: member.DeleteMemberRes
	(*CreateMemberGroupReq)(nil),   // 16: member.CreateMemberGroupReq
	(*CreateMemberGroupRes)(nil),   // 17: member.CreateMemberGroupRes
	(*GetMemberGroupsReq)(nil),     // 18: member.GetMemberGroupsReq
	(*MemberGroup)(nil),            // 19: member.MemberGroup
	(*GetMemberGroupsRes)(nil),     // 20: member.GetMemberGroupsRes
	(*DeleteMemberGroupReq)(nil),   // 21: member.DeleteMemberGroupReq
	(*DeleteMemberGroupRes)(nil),   // 22: member.DeleteMemberGroupRes
	(*general.Pagination)(nil),     // 23: general.Pagination
	(*general.PaginationInfo)(nil), // 24: general.PaginationInfo
}
var file_member_member_proto_depIdxs = []int32{
	0,  // 0: member.Member.status:type_name -> member.StatusType
	1,  // 1: member.Member.verifyStatus:type_name -> member.VerifyStatus
	0,  // 2: member.CreateMemberReq.status:type_name -> member.StatusType
	1,  // 3: member.CreateMemberReq.verifyStatus:type_name -> member.VerifyStatus
	3,  // 4: member.GetMemberRes.member:type_name -> member.Member
	23, // 5: member.GetMembersReq.pagination:type_name -> general.Pagination
	3,  // 6: member.GetMembersRes.member:type_name -> member.Member
	24, // 7: member.GetMembersRes.paginationInfo:type_name -> general.PaginationInfo
	0,  // 8: member.ModifyMemberReq.status:type_name -> member.StatusType
	1,  // 9: member.ModifyMemberReq.verifyStatus:type_name -> member.VerifyStatus
	2,  // 10: member.ResetPasswordReq.verifyType:type_name -> member.VerifyType
	19, // 11: member.GetMemberGroupsRes.memberGroups:type_name -> member.MemberGroup
	4,  // 12: member.MemberService.CreateMember:input_type -> member.CreateMemberReq
	6,  // 13: member.MemberService.GetMember:input_type -> member.GetMemberReq
	8,  // 14: member.MemberService.GetMembers:input_type -> member.GetMembersReq
	10, // 15: member.MemberService.ModifyMember:input_type -> member.ModifyMemberReq
	12, // 16: member.MemberService.ResetPassword:input_type -> member.ResetPasswordReq
	14, // 17: member.MemberService.DeleteMember:input_type -> member.DeleteMemberReq
	16, // 18: member.MemberService.CreateMemberGroup:input_type -> member.CreateMemberGroupReq
	18, // 19: member.MemberService.GetMemberGroups:input_type -> member.GetMemberGroupsReq
	21, // 20: member.MemberService.DeleteMemberGroup:input_type -> member.DeleteMemberGroupReq
	5,  // 21: member.MemberService.CreateMember:output_type -> member.CreateMemberRes
	7,  // 22: member.MemberService.GetMember:output_type -> member.GetMemberRes
	9,  // 23: member.MemberService.GetMembers:output_type -> member.GetMembersRes
	11, // 24: member.MemberService.ModifyMember:output_type -> member.ModifyMemberRes
	13, // 25: member.MemberService.ResetPassword:output_type -> member.ResetPasswordRes
	15, // 26: member.MemberService.DeleteMember:output_type -> member.DeleteMemberRes
	17, // 27: member.MemberService.CreateMemberGroup:output_type -> member.CreateMemberGroupRes
	20, // 28: member.MemberService.GetMemberGroups:output_type -> member.GetMemberGroupsRes
	22, // 29: member.MemberService.DeleteMemberGroup:output_type -> member.DeleteMemberGroupRes
	21, // [21:30] is the sub-list for method output_type
	12, // [12:21] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_member_member_proto_init() }
func file_member_member_proto_init() {
	if File_member_member_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_member_member_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Member); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_member_member_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateMemberReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_member_member_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateMemberRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_member_member_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMemberReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_member_member_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMemberRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_member_member_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMembersReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_member_member_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMembersRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_member_member_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModifyMemberReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_member_member_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModifyMemberRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_member_member_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResetPasswordReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_member_member_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResetPasswordRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_member_member_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteMemberReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_member_member_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteMemberRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_member_member_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateMemberGroupReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_member_member_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateMemberGroupRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_member_member_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMemberGroupsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_member_member_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MemberGroup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_member_member_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMemberGroupsRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_member_member_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteMemberGroupReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_member_member_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteMemberGroupRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_member_member_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*GetMemberReq_Id)(nil),
		(*GetMemberReq_Account)(nil),
		(*GetMemberReq_Mail)(nil),
		(*GetMemberReq_LineID)(nil),
	}
	file_member_member_proto_msgTypes[7].OneofWrappers = []interface{}{
		(*ModifyMemberReq_Id)(nil),
		(*ModifyMemberReq_Account)(nil),
		(*ModifyMemberReq_Mail)(nil),
		(*ModifyMemberReq_LineID)(nil),
	}
	file_member_member_proto_msgTypes[11].OneofWrappers = []interface{}{
		(*DeleteMemberReq_Id)(nil),
		(*DeleteMemberReq_Account)(nil),
		(*DeleteMemberReq_Mail)(nil),
		(*DeleteMemberReq_LineID)(nil),
	}
	file_member_member_proto_msgTypes[15].OneofWrappers = []interface{}{}
	file_member_member_proto_msgTypes[18].OneofWrappers = []interface{}{
		(*DeleteMemberGroupReq_Id)(nil),
		(*DeleteMemberGroupReq_Name)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_member_member_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_member_member_proto_goTypes,
		DependencyIndexes: file_member_member_proto_depIdxs,
		EnumInfos:         file_member_member_proto_enumTypes,
		MessageInfos:      file_member_member_proto_msgTypes,
	}.Build()
	File_member_member_proto = out.File
	file_member_member_proto_rawDesc = nil
	file_member_member_proto_goTypes = nil
	file_member_member_proto_depIdxs = nil
}
