// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.15.8
// source: quote/quote.proto

package quote

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// QuoteServiceClient is the client API for QuoteService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QuoteServiceClient interface {
	AddProductQuoteSources(ctx context.Context, in *AddProductQuoteSourcesReq, opts ...grpc.CallOption) (*AddProductQuoteSourcesRes, error)
	ModifyProductQuoteSource(ctx context.Context, in *ModifyProductQuoteSourceReq, opts ...grpc.CallOption) (*ModifyProductQuoteSourceRes, error)
	GetQuotes(ctx context.Context, in *GetQuotesReq, opts ...grpc.CallOption) (*GetQuotesRes, error)
	DeleteQuotes(ctx context.Context, in *DeleteQuotesReq, opts ...grpc.CallOption) (*DeleteQuotesRes, error)
}

type quoteServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewQuoteServiceClient(cc grpc.ClientConnInterface) QuoteServiceClient {
	return &quoteServiceClient{cc}
}

func (c *quoteServiceClient) AddProductQuoteSources(ctx context.Context, in *AddProductQuoteSourcesReq, opts ...grpc.CallOption) (*AddProductQuoteSourcesRes, error) {
	out := new(AddProductQuoteSourcesRes)
	err := c.cc.Invoke(ctx, "/quote.QuoteService/AddProductQuoteSources", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quoteServiceClient) ModifyProductQuoteSource(ctx context.Context, in *ModifyProductQuoteSourceReq, opts ...grpc.CallOption) (*ModifyProductQuoteSourceRes, error) {
	out := new(ModifyProductQuoteSourceRes)
	err := c.cc.Invoke(ctx, "/quote.QuoteService/ModifyProductQuoteSource", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quoteServiceClient) GetQuotes(ctx context.Context, in *GetQuotesReq, opts ...grpc.CallOption) (*GetQuotesRes, error) {
	out := new(GetQuotesRes)
	err := c.cc.Invoke(ctx, "/quote.QuoteService/GetQuotes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quoteServiceClient) DeleteQuotes(ctx context.Context, in *DeleteQuotesReq, opts ...grpc.CallOption) (*DeleteQuotesRes, error) {
	out := new(DeleteQuotesRes)
	err := c.cc.Invoke(ctx, "/quote.QuoteService/DeleteQuotes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QuoteServiceServer is the server API for QuoteService service.
// All implementations should embed UnimplementedQuoteServiceServer
// for forward compatibility
type QuoteServiceServer interface {
	AddProductQuoteSources(context.Context, *AddProductQuoteSourcesReq) (*AddProductQuoteSourcesRes, error)
	ModifyProductQuoteSource(context.Context, *ModifyProductQuoteSourceReq) (*ModifyProductQuoteSourceRes, error)
	GetQuotes(context.Context, *GetQuotesReq) (*GetQuotesRes, error)
	DeleteQuotes(context.Context, *DeleteQuotesReq) (*DeleteQuotesRes, error)
}

// UnimplementedQuoteServiceServer should be embedded to have forward compatible implementations.
type UnimplementedQuoteServiceServer struct {
}

func (UnimplementedQuoteServiceServer) AddProductQuoteSources(context.Context, *AddProductQuoteSourcesReq) (*AddProductQuoteSourcesRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddProductQuoteSources not implemented")
}
func (UnimplementedQuoteServiceServer) ModifyProductQuoteSource(context.Context, *ModifyProductQuoteSourceReq) (*ModifyProductQuoteSourceRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ModifyProductQuoteSource not implemented")
}
func (UnimplementedQuoteServiceServer) GetQuotes(context.Context, *GetQuotesReq) (*GetQuotesRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetQuotes not implemented")
}
func (UnimplementedQuoteServiceServer) DeleteQuotes(context.Context, *DeleteQuotesReq) (*DeleteQuotesRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteQuotes not implemented")
}

// UnsafeQuoteServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QuoteServiceServer will
// result in compilation errors.
type UnsafeQuoteServiceServer interface {
	mustEmbedUnimplementedQuoteServiceServer()
}

func RegisterQuoteServiceServer(s grpc.ServiceRegistrar, srv QuoteServiceServer) {
	s.RegisterService(&QuoteService_ServiceDesc, srv)
}

func _QuoteService_AddProductQuoteSources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddProductQuoteSourcesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuoteServiceServer).AddProductQuoteSources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/quote.QuoteService/AddProductQuoteSources",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuoteServiceServer).AddProductQuoteSources(ctx, req.(*AddProductQuoteSourcesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuoteService_ModifyProductQuoteSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModifyProductQuoteSourceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuoteServiceServer).ModifyProductQuoteSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/quote.QuoteService/ModifyProductQuoteSource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuoteServiceServer).ModifyProductQuoteSource(ctx, req.(*ModifyProductQuoteSourceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuoteService_GetQuotes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetQuotesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuoteServiceServer).GetQuotes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/quote.QuoteService/GetQuotes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuoteServiceServer).GetQuotes(ctx, req.(*GetQuotesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuoteService_DeleteQuotes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteQuotesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuoteServiceServer).DeleteQuotes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/quote.QuoteService/DeleteQuotes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuoteServiceServer).DeleteQuotes(ctx, req.(*DeleteQuotesReq))
	}
	return interceptor(ctx, in, info, handler)
}

// QuoteService_ServiceDesc is the grpc.ServiceDesc for QuoteService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QuoteService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "quote.QuoteService",
	HandlerType: (*QuoteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddProductQuoteSources",
			Handler:    _QuoteService_AddProductQuoteSources_Handler,
		},
		{
			MethodName: "ModifyProductQuoteSource",
			Handler:    _QuoteService_ModifyProductQuoteSource_Handler,
		},
		{
			MethodName: "GetQuotes",
			Handler:    _QuoteService_GetQuotes_Handler,
		},
		{
			MethodName: "DeleteQuotes",
			Handler:    _QuoteService_DeleteQuotes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "quote/quote.proto",
}
