// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.15.8
// source: quote/quote.proto

package quote

import (
	product "github.com/paper-trade-chatbot/be-proto/product"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetQuotesReq_GetFlags int32

const (
	GetQuotesReq_GetFlag_None  GetQuotesReq_GetFlags = 0
	GetQuotesReq_GetFlag_Quote GetQuotesReq_GetFlags = 1
	GetQuotesReq_GetFlag_Ask   GetQuotesReq_GetFlags = 2
	GetQuotesReq_GetFlag_Bid   GetQuotesReq_GetFlags = 4
)

// Enum value maps for GetQuotesReq_GetFlags.
var (
	GetQuotesReq_GetFlags_name = map[int32]string{
		0: "GetFlag_None",
		1: "GetFlag_Quote",
		2: "GetFlag_Ask",
		4: "GetFlag_Bid",
	}
	GetQuotesReq_GetFlags_value = map[string]int32{
		"GetFlag_None":  0,
		"GetFlag_Quote": 1,
		"GetFlag_Ask":   2,
		"GetFlag_Bid":   4,
	}
)

func (x GetQuotesReq_GetFlags) Enum() *GetQuotesReq_GetFlags {
	p := new(GetQuotesReq_GetFlags)
	*p = x
	return p
}

func (x GetQuotesReq_GetFlags) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetQuotesReq_GetFlags) Descriptor() protoreflect.EnumDescriptor {
	return file_quote_quote_proto_enumTypes[0].Descriptor()
}

func (GetQuotesReq_GetFlags) Type() protoreflect.EnumType {
	return &file_quote_quote_proto_enumTypes[0]
}

func (x GetQuotesReq_GetFlags) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetQuotesReq_GetFlags.Descriptor instead.
func (GetQuotesReq_GetFlags) EnumDescriptor() ([]byte, []int) {
	return file_quote_quote_proto_rawDescGZIP(), []int{5, 0}
}

type AddProductQuoteSourcesReqItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProductID    int64               `protobuf:"varint,1,opt,name=productID,proto3" json:"productID,omitempty"`
	Type         product.ProductType `protobuf:"varint,2,opt,name=type,proto3,enum=product.ProductType" json:"type,omitempty"`
	SourceCode   string              `protobuf:"bytes,3,opt,name=sourceCode,proto3" json:"sourceCode,omitempty"`
	QuoteCode    string              `protobuf:"bytes,4,opt,name=quoteCode,proto3" json:"quoteCode,omitempty"`
	CurrencyCode string              `protobuf:"bytes,5,opt,name=currencyCode,proto3" json:"currencyCode,omitempty"`
	Status       product.Status      `protobuf:"varint,6,opt,name=status,proto3,enum=product.Status" json:"status,omitempty"`
}

func (x *AddProductQuoteSourcesReqItem) Reset() {
	*x = AddProductQuoteSourcesReqItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quote_quote_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddProductQuoteSourcesReqItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProductQuoteSourcesReqItem) ProtoMessage() {}

func (x *AddProductQuoteSourcesReqItem) ProtoReflect() protoreflect.Message {
	mi := &file_quote_quote_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProductQuoteSourcesReqItem.ProtoReflect.Descriptor instead.
func (*AddProductQuoteSourcesReqItem) Descriptor() ([]byte, []int) {
	return file_quote_quote_proto_rawDescGZIP(), []int{0}
}

func (x *AddProductQuoteSourcesReqItem) GetProductID() int64 {
	if x != nil {
		return x.ProductID
	}
	return 0
}

func (x *AddProductQuoteSourcesReqItem) GetType() product.ProductType {
	if x != nil {
		return x.Type
	}
	return product.ProductType(0)
}

func (x *AddProductQuoteSourcesReqItem) GetSourceCode() string {
	if x != nil {
		return x.SourceCode
	}
	return ""
}

func (x *AddProductQuoteSourcesReqItem) GetQuoteCode() string {
	if x != nil {
		return x.QuoteCode
	}
	return ""
}

func (x *AddProductQuoteSourcesReqItem) GetCurrencyCode() string {
	if x != nil {
		return x.CurrencyCode
	}
	return ""
}

func (x *AddProductQuoteSourcesReqItem) GetStatus() product.Status {
	if x != nil {
		return x.Status
	}
	return product.Status(0)
}

type AddProductQuoteSourcesReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Products []*AddProductQuoteSourcesReqItem `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
}

func (x *AddProductQuoteSourcesReq) Reset() {
	*x = AddProductQuoteSourcesReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quote_quote_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddProductQuoteSourcesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProductQuoteSourcesReq) ProtoMessage() {}

func (x *AddProductQuoteSourcesReq) ProtoReflect() protoreflect.Message {
	mi := &file_quote_quote_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProductQuoteSourcesReq.ProtoReflect.Descriptor instead.
func (*AddProductQuoteSourcesReq) Descriptor() ([]byte, []int) {
	return file_quote_quote_proto_rawDescGZIP(), []int{1}
}

func (x *AddProductQuoteSourcesReq) GetProducts() []*AddProductQuoteSourcesReqItem {
	if x != nil {
		return x.Products
	}
	return nil
}

type AddProductQuoteSourcesRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddProductQuoteSourcesRes) Reset() {
	*x = AddProductQuoteSourcesRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quote_quote_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddProductQuoteSourcesRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProductQuoteSourcesRes) ProtoMessage() {}

func (x *AddProductQuoteSourcesRes) ProtoReflect() protoreflect.Message {
	mi := &file_quote_quote_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProductQuoteSourcesRes.ProtoReflect.Descriptor instead.
func (*AddProductQuoteSourcesRes) Descriptor() ([]byte, []int) {
	return file_quote_quote_proto_rawDescGZIP(), []int{2}
}

type ModifyProductQuoteSourceReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProductID    int64               `protobuf:"varint,1,opt,name=productID,proto3" json:"productID,omitempty"`
	Type         product.ProductType `protobuf:"varint,2,opt,name=type,proto3,enum=product.ProductType" json:"type,omitempty"`
	SourceCode   string              `protobuf:"bytes,3,opt,name=sourceCode,proto3" json:"sourceCode,omitempty"`
	QuoteCode    string              `protobuf:"bytes,4,opt,name=quoteCode,proto3" json:"quoteCode,omitempty"`
	CurrencyCode string              `protobuf:"bytes,5,opt,name=currencyCode,proto3" json:"currencyCode,omitempty"`
	Status       product.Status      `protobuf:"varint,6,opt,name=status,proto3,enum=product.Status" json:"status,omitempty"`
}

func (x *ModifyProductQuoteSourceReq) Reset() {
	*x = ModifyProductQuoteSourceReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quote_quote_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModifyProductQuoteSourceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyProductQuoteSourceReq) ProtoMessage() {}

func (x *ModifyProductQuoteSourceReq) ProtoReflect() protoreflect.Message {
	mi := &file_quote_quote_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyProductQuoteSourceReq.ProtoReflect.Descriptor instead.
func (*ModifyProductQuoteSourceReq) Descriptor() ([]byte, []int) {
	return file_quote_quote_proto_rawDescGZIP(), []int{3}
}

func (x *ModifyProductQuoteSourceReq) GetProductID() int64 {
	if x != nil {
		return x.ProductID
	}
	return 0
}

func (x *ModifyProductQuoteSourceReq) GetType() product.ProductType {
	if x != nil {
		return x.Type
	}
	return product.ProductType(0)
}

func (x *ModifyProductQuoteSourceReq) GetSourceCode() string {
	if x != nil {
		return x.SourceCode
	}
	return ""
}

func (x *ModifyProductQuoteSourceReq) GetQuoteCode() string {
	if x != nil {
		return x.QuoteCode
	}
	return ""
}

func (x *ModifyProductQuoteSourceReq) GetCurrencyCode() string {
	if x != nil {
		return x.CurrencyCode
	}
	return ""
}

func (x *ModifyProductQuoteSourceReq) GetStatus() product.Status {
	if x != nil {
		return x.Status
	}
	return product.Status(0)
}

type ModifyProductQuoteSourceRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ModifyProductQuoteSourceRes) Reset() {
	*x = ModifyProductQuoteSourceRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quote_quote_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModifyProductQuoteSourceRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyProductQuoteSourceRes) ProtoMessage() {}

func (x *ModifyProductQuoteSourceRes) ProtoReflect() protoreflect.Message {
	mi := &file_quote_quote_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyProductQuoteSourceRes.ProtoReflect.Descriptor instead.
func (*ModifyProductQuoteSourceRes) Descriptor() ([]byte, []int) {
	return file_quote_quote_proto_rawDescGZIP(), []int{4}
}

type GetQuotesReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProductIDs []int64               `protobuf:"varint,1,rep,packed,name=productIDs,proto3" json:"productIDs,omitempty"`
	Flag       GetQuotesReq_GetFlags `protobuf:"varint,2,opt,name=flag,proto3,enum=quote.GetQuotesReq_GetFlags" json:"flag,omitempty"`
	GetFrom    *string               `protobuf:"bytes,3,opt,name=getFrom,proto3,oneof" json:"getFrom,omitempty"` //HHMMSS
	GetTo      *string               `protobuf:"bytes,4,opt,name=getTo,proto3,oneof" json:"getTo,omitempty"`     //HHMMSS
}

func (x *GetQuotesReq) Reset() {
	*x = GetQuotesReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quote_quote_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetQuotesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuotesReq) ProtoMessage() {}

func (x *GetQuotesReq) ProtoReflect() protoreflect.Message {
	mi := &file_quote_quote_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuotesReq.ProtoReflect.Descriptor instead.
func (*GetQuotesReq) Descriptor() ([]byte, []int) {
	return file_quote_quote_proto_rawDescGZIP(), []int{5}
}

func (x *GetQuotesReq) GetProductIDs() []int64 {
	if x != nil {
		return x.ProductIDs
	}
	return nil
}

func (x *GetQuotesReq) GetFlag() GetQuotesReq_GetFlags {
	if x != nil {
		return x.Flag
	}
	return GetQuotesReq_GetFlag_None
}

func (x *GetQuotesReq) GetGetFrom() string {
	if x != nil && x.GetFrom != nil {
		return *x.GetFrom
	}
	return ""
}

func (x *GetQuotesReq) GetGetTo() string {
	if x != nil && x.GetTo != nil {
		return *x.GetTo
	}
	return ""
}

type GetQuotesResItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProductID int64             `protobuf:"varint,1,opt,name=productID,proto3" json:"productID,omitempty"`
	Quotes    map[string]string `protobuf:"bytes,2,rep,name=quotes,proto3" json:"quotes,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *GetQuotesResItem) Reset() {
	*x = GetQuotesResItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quote_quote_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetQuotesResItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuotesResItem) ProtoMessage() {}

func (x *GetQuotesResItem) ProtoReflect() protoreflect.Message {
	mi := &file_quote_quote_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuotesResItem.ProtoReflect.Descriptor instead.
func (*GetQuotesResItem) Descriptor() ([]byte, []int) {
	return file_quote_quote_proto_rawDescGZIP(), []int{6}
}

func (x *GetQuotesResItem) GetProductID() int64 {
	if x != nil {
		return x.ProductID
	}
	return 0
}

func (x *GetQuotesResItem) GetQuotes() map[string]string {
	if x != nil {
		return x.Quotes
	}
	return nil
}

type GetQuotesRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Quotes []*GetQuotesResItem `protobuf:"bytes,1,rep,name=quotes,proto3" json:"quotes,omitempty"`
}

func (x *GetQuotesRes) Reset() {
	*x = GetQuotesRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quote_quote_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetQuotesRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuotesRes) ProtoMessage() {}

func (x *GetQuotesRes) ProtoReflect() protoreflect.Message {
	mi := &file_quote_quote_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuotesRes.ProtoReflect.Descriptor instead.
func (*GetQuotesRes) Descriptor() ([]byte, []int) {
	return file_quote_quote_proto_rawDescGZIP(), []int{7}
}

func (x *GetQuotesRes) GetQuotes() []*GetQuotesResItem {
	if x != nil {
		return x.Quotes
	}
	return nil
}

type DeleteQuotesReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProductIDs []int64 `protobuf:"varint,1,rep,packed,name=productIDs,proto3" json:"productIDs,omitempty"`
	DeleteFrom string  `protobuf:"bytes,2,opt,name=deleteFrom,proto3" json:"deleteFrom,omitempty"` // HHMMSS, not include itself
	DeleteTo   string  `protobuf:"bytes,3,opt,name=deleteTo,proto3" json:"deleteTo,omitempty"`     // HHMMSS, include ifself
}

func (x *DeleteQuotesReq) Reset() {
	*x = DeleteQuotesReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quote_quote_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteQuotesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteQuotesReq) ProtoMessage() {}

func (x *DeleteQuotesReq) ProtoReflect() protoreflect.Message {
	mi := &file_quote_quote_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteQuotesReq.ProtoReflect.Descriptor instead.
func (*DeleteQuotesReq) Descriptor() ([]byte, []int) {
	return file_quote_quote_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteQuotesReq) GetProductIDs() []int64 {
	if x != nil {
		return x.ProductIDs
	}
	return nil
}

func (x *DeleteQuotesReq) GetDeleteFrom() string {
	if x != nil {
		return x.DeleteFrom
	}
	return ""
}

func (x *DeleteQuotesReq) GetDeleteTo() string {
	if x != nil {
		return x.DeleteTo
	}
	return ""
}

type DeleteQuotesRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteQuotesRes) Reset() {
	*x = DeleteQuotesRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quote_quote_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteQuotesRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteQuotesRes) ProtoMessage() {}

func (x *DeleteQuotesRes) ProtoReflect() protoreflect.Message {
	mi := &file_quote_quote_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteQuotesRes.ProtoReflect.Descriptor instead.
func (*DeleteQuotesRes) Descriptor() ([]byte, []int) {
	return file_quote_quote_proto_rawDescGZIP(), []int{9}
}

var File_quote_quote_proto protoreflect.FileDescriptor

var file_quote_quote_proto_rawDesc = []byte{
	0x0a, 0x11, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x2f, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x1a, 0x15, 0x70, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xf2, 0x01, 0x0a, 0x1d, 0x41, 0x64, 0x64, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x51, 0x75, 0x6f, 0x74, 0x65, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x52, 0x65, 0x71, 0x49,
	0x74, 0x65, 0x6d, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49,
	0x44, 0x12, 0x28, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x14, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x71,
	0x75, 0x6f, 0x74, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x71, 0x75, 0x6f, 0x74, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x75, 0x72,
	0x72, 0x65, 0x6e, 0x63, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x27, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e,
	0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x5d, 0x0a, 0x19, 0x41, 0x64, 0x64, 0x50, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73,
	0x52, 0x65, 0x71, 0x12, 0x40, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x2e, 0x41, 0x64,
	0x64, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x53, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x73, 0x52, 0x65, 0x71, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x08, 0x70, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x73, 0x22, 0x1b, 0x0a, 0x19, 0x41, 0x64, 0x64, 0x50, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x52,
	0x65, 0x73, 0x22, 0xf0, 0x01, 0x0a, 0x1b, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x50, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52,
	0x65, 0x71, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x44,
	0x12, 0x28, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14,
	0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x71, 0x75,
	0x6f, 0x74, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x71,
	0x75, 0x6f, 0x74, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x75, 0x72, 0x72,
	0x65, 0x6e, 0x63, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x27, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x70,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x1d, 0x0a, 0x1b, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x50,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x53, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x52, 0x65, 0x73, 0x22, 0x83, 0x02, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x51, 0x75, 0x6f, 0x74,
	0x65, 0x73, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x49, 0x44, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x49, 0x44, 0x73, 0x12, 0x30, 0x0a, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x51,
	0x75, 0x6f, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x6c, 0x61, 0x67,
	0x73, 0x52, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x12, 0x1d, 0x0a, 0x07, 0x67, 0x65, 0x74, 0x46, 0x72,
	0x6f, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x07, 0x67, 0x65, 0x74, 0x46,
	0x72, 0x6f, 0x6d, 0x88, 0x01, 0x01, 0x12, 0x19, 0x0a, 0x05, 0x67, 0x65, 0x74, 0x54, 0x6f, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x05, 0x67, 0x65, 0x74, 0x54, 0x6f, 0x88, 0x01,
	0x01, 0x22, 0x51, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x46, 0x6c, 0x61, 0x67, 0x73, 0x12, 0x10, 0x0a,
	0x0c, 0x47, 0x65, 0x74, 0x46, 0x6c, 0x61, 0x67, 0x5f, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12,
	0x11, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x46, 0x6c, 0x61, 0x67, 0x5f, 0x51, 0x75, 0x6f, 0x74, 0x65,
	0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x46, 0x6c, 0x61, 0x67, 0x5f, 0x41, 0x73,
	0x6b, 0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x46, 0x6c, 0x61, 0x67, 0x5f, 0x42,
	0x69, 0x64, 0x10, 0x04, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x67, 0x65, 0x74, 0x46, 0x72, 0x6f, 0x6d,
	0x42, 0x08, 0x0a, 0x06, 0x5f, 0x67, 0x65, 0x74, 0x54, 0x6f, 0x22, 0xa8, 0x01, 0x0a, 0x10, 0x47,
	0x65, 0x74, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x49, 0x74, 0x65, 0x6d, 0x12,
	0x1c, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x44, 0x12, 0x3b, 0x0a,
	0x06, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e,
	0x71, 0x75, 0x6f, 0x74, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x73, 0x52,
	0x65, 0x73, 0x49, 0x74, 0x65, 0x6d, 0x2e, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x73, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x52, 0x06, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x73, 0x1a, 0x39, 0x0a, 0x0b, 0x51, 0x75,
	0x6f, 0x74, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x3f, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x51, 0x75, 0x6f, 0x74,
	0x65, 0x73, 0x52, 0x65, 0x73, 0x12, 0x2f, 0x0a, 0x06, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x2e, 0x47, 0x65,
	0x74, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x06,
	0x71, 0x75, 0x6f, 0x74, 0x65, 0x73, 0x22, 0x6d, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x51, 0x75, 0x6f, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x49, 0x44, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x0a, 0x70,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x44, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x54, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x54, 0x6f, 0x22, 0x11, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x51,
	0x75, 0x6f, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x32, 0xc7, 0x02, 0x0a, 0x0c, 0x51, 0x75, 0x6f,
	0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5c, 0x0a, 0x16, 0x41, 0x64, 0x64,
	0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x53, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x73, 0x12, 0x20, 0x2e, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x2e, 0x41, 0x64, 0x64, 0x50,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x53, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x20, 0x2e, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x2e, 0x41, 0x64,
	0x64, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x53, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x73, 0x52, 0x65, 0x73, 0x12, 0x62, 0x0a, 0x18, 0x4d, 0x6f, 0x64, 0x69, 0x66,
	0x79, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x53, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x12, 0x22, 0x2e, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x2e, 0x4d, 0x6f, 0x64, 0x69,
	0x66, 0x79, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x53, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x22, 0x2e, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x2e,
	0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x51, 0x75, 0x6f,
	0x74, 0x65, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x73, 0x12, 0x35, 0x0a, 0x09, 0x47,
	0x65, 0x74, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x73, 0x12, 0x13, 0x2e, 0x71, 0x75, 0x6f, 0x74, 0x65,
	0x2e, 0x47, 0x65, 0x74, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e,
	0x71, 0x75, 0x6f, 0x74, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x73, 0x52,
	0x65, 0x73, 0x12, 0x3e, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x51, 0x75, 0x6f, 0x74,
	0x65, 0x73, 0x12, 0x16, 0x2e, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x71, 0x75, 0x6f,
	0x74, 0x65, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x73, 0x52,
	0x65, 0x73, 0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x70, 0x61, 0x70, 0x65, 0x72, 0x2d, 0x74, 0x72, 0x61, 0x64, 0x65, 0x2d, 0x63, 0x68, 0x61,
	0x74, 0x62, 0x6f, 0x74, 0x2f, 0x62, 0x65, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x71, 0x75,
	0x6f, 0x74, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_quote_quote_proto_rawDescOnce sync.Once
	file_quote_quote_proto_rawDescData = file_quote_quote_proto_rawDesc
)

func file_quote_quote_proto_rawDescGZIP() []byte {
	file_quote_quote_proto_rawDescOnce.Do(func() {
		file_quote_quote_proto_rawDescData = protoimpl.X.CompressGZIP(file_quote_quote_proto_rawDescData)
	})
	return file_quote_quote_proto_rawDescData
}

var file_quote_quote_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_quote_quote_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_quote_quote_proto_goTypes = []interface{}{
	(GetQuotesReq_GetFlags)(0),            // 0: quote.GetQuotesReq.GetFlags
	(*AddProductQuoteSourcesReqItem)(nil), // 1: quote.AddProductQuoteSourcesReqItem
	(*AddProductQuoteSourcesReq)(nil),     // 2: quote.AddProductQuoteSourcesReq
	(*AddProductQuoteSourcesRes)(nil),     // 3: quote.AddProductQuoteSourcesRes
	(*ModifyProductQuoteSourceReq)(nil),   // 4: quote.ModifyProductQuoteSourceReq
	(*ModifyProductQuoteSourceRes)(nil),   // 5: quote.ModifyProductQuoteSourceRes
	(*GetQuotesReq)(nil),                  // 6: quote.GetQuotesReq
	(*GetQuotesResItem)(nil),              // 7: quote.GetQuotesResItem
	(*GetQuotesRes)(nil),                  // 8: quote.GetQuotesRes
	(*DeleteQuotesReq)(nil),               // 9: quote.DeleteQuotesReq
	(*DeleteQuotesRes)(nil),               // 10: quote.DeleteQuotesRes
	nil,                                   // 11: quote.GetQuotesResItem.QuotesEntry
	(product.ProductType)(0),              // 12: product.ProductType
	(product.Status)(0),                   // 13: product.Status
}
var file_quote_quote_proto_depIdxs = []int32{
	12, // 0: quote.AddProductQuoteSourcesReqItem.type:type_name -> product.ProductType
	13, // 1: quote.AddProductQuoteSourcesReqItem.status:type_name -> product.Status
	1,  // 2: quote.AddProductQuoteSourcesReq.products:type_name -> quote.AddProductQuoteSourcesReqItem
	12, // 3: quote.ModifyProductQuoteSourceReq.type:type_name -> product.ProductType
	13, // 4: quote.ModifyProductQuoteSourceReq.status:type_name -> product.Status
	0,  // 5: quote.GetQuotesReq.flag:type_name -> quote.GetQuotesReq.GetFlags
	11, // 6: quote.GetQuotesResItem.quotes:type_name -> quote.GetQuotesResItem.QuotesEntry
	7,  // 7: quote.GetQuotesRes.quotes:type_name -> quote.GetQuotesResItem
	2,  // 8: quote.QuoteService.AddProductQuoteSources:input_type -> quote.AddProductQuoteSourcesReq
	4,  // 9: quote.QuoteService.ModifyProductQuoteSource:input_type -> quote.ModifyProductQuoteSourceReq
	6,  // 10: quote.QuoteService.GetQuotes:input_type -> quote.GetQuotesReq
	9,  // 11: quote.QuoteService.DeleteQuotes:input_type -> quote.DeleteQuotesReq
	3,  // 12: quote.QuoteService.AddProductQuoteSources:output_type -> quote.AddProductQuoteSourcesRes
	5,  // 13: quote.QuoteService.ModifyProductQuoteSource:output_type -> quote.ModifyProductQuoteSourceRes
	8,  // 14: quote.QuoteService.GetQuotes:output_type -> quote.GetQuotesRes
	10, // 15: quote.QuoteService.DeleteQuotes:output_type -> quote.DeleteQuotesRes
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_quote_quote_proto_init() }
func file_quote_quote_proto_init() {
	if File_quote_quote_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_quote_quote_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddProductQuoteSourcesReqItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quote_quote_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddProductQuoteSourcesReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quote_quote_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddProductQuoteSourcesRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quote_quote_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModifyProductQuoteSourceReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quote_quote_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModifyProductQuoteSourceRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quote_quote_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetQuotesReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quote_quote_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetQuotesResItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quote_quote_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetQuotesRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quote_quote_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteQuotesReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quote_quote_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteQuotesRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_quote_quote_proto_msgTypes[5].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_quote_quote_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_quote_quote_proto_goTypes,
		DependencyIndexes: file_quote_quote_proto_depIdxs,
		EnumInfos:         file_quote_quote_proto_enumTypes,
		MessageInfos:      file_quote_quote_proto_msgTypes,
	}.Build()
	File_quote_quote_proto = out.File
	file_quote_quote_proto_rawDesc = nil
	file_quote_quote_proto_goTypes = nil
	file_quote_quote_proto_depIdxs = nil
}
